language: node_js
node_js:
  - "6.9"

os:
  - linux

before_install:
  - npm install -g vsce
  - npm install -g typescript
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

install:
  - npm install
  - vsce package

script:
  - npm test --silent

# safelist
branches:
  only:
  - master
