language: node_js

node_js:
- '6'

os:
- linux
- osx

branches:
  only:
  - master
  - "/v?\\d+\\.\\d+(\\.\\d+)?/"

env:
  global:
    secure: ApAlOobnbBReuScbZXn4GP8bRnuTmik0jYE3jBb3+wCcu4ksaTwL/pzqOp4qfHer5QZZJ08vw+5L6Rag7gEffLKvxH2ot/Jx5zN1qSr3UbQrJeIn5mwgML2dggQzZPKZ37e9mJcS8WiuR2TGgMluTgRaLFBKH6QLp9puKUAg/f9tHypr83sDzgDFQAl0H3Kwu1ndjdr4zdR9/sQ+xSgNirA2kGNIv5k3XkQ+TXjgw9Zrdb3qrS+h/5a8iR/JgSnxNoKlyZtksbH4+N8FUaZtfFZqDEJ98/1V45AVZuOhFStpyxa2omq4Ugkwcm67fjqdkaYTV0atQeUiZ5dcFrjzIfB06AU3FGrMQ2aPTH/MyLsZSFLkDm7sBYVlfegLEGOp+AUhqOC7D8G+YdPJJw8B3Of6HhG5ei/vHXuJ3xxiIic3J97aZIklmSYsx4psusTmfiJDPRpVI3OmULOGH+HlU8y14Z5Ikdd0sOM5H354bVZpKEPhvtcJefJszx6THRyd4YFxoccSV9cf2sLSMFTMCtCq11S9WKhx2cMNOI2nF7vncX3/u7Z1Oi/hAKyyvBBOW7kgcsm3BEyuxtLPVjhzr6GQQBGXm9k35LhdGz3SGh+EODHAv1px0cUg0eNvJxEz4Gf2YsXYRbo8WlycehNVrrG+FCmMXapRcXI4DjqSFd8=

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi

install:
- npm install -g typescript
- npm install -g gulp
- npm install
- npm run vscode:prepublish

script:
- npm test --silent
- gulp package --tag $TRAVIS_TAG --pullRequest $TRAVIS_PULL_REQUEST --branch $TRAVIS_BRANCH
- gulp upload --azureConnectionString $azureConnectionString

deploy:
  provider: releases
  api_key:
    secure: gZRyzuPpeEdPzRRQR8UlXJhkB7FjWvuOjwMR80nVj7sjOAkiOdmdrMSeMzOpyhQv6AXQZ+sY9kBE2+yIOpkrSbtSWsBSVqwajNIiSRHc78m/W1RFFm1STtIHeYorSF4TiAHux6o5qAVkWKRLZJa+YM0XDRP3fAkY4LR2oq5hEbnqGvpD0CnbIwrpQXngP+khY7WtZ/QLr1MG9YGCMIsFo+avI1KbaOEh85uHn12YQkNfmtJudxAspMAyT6ODjnnY0XUXX5wpCTMJcP+UCI4hEYqlmU9W6XF3UfDpoRcSXONdfCvzpN5X1szCfMIbuW0hy89XL2cAuW82ZtTADqjIO1pRmYvCR0P0vNlcb+9LlEPzE2ltoommbH/5/ELnACChVcnDgGDdlPS6lxokQih2ihDXWNZuW71A6VsoXqx3WlOTaYWYSa/B1WYdZ2kzfGtaU4H3CQZxqZtSEnFAdFXiQbeH1/AJJcRTxStVtxPVfzgHgyJMlNbIx9gyb/QxsVMit3gUHQnYj3ujw32P0qvX5qcHoqktV4IBPK50d1Gli4KPhH8VkdaRyl1e2z2el0u8Jy7ZexFgilbcJNoJp9X3Qa6kYLHcpTu/5Mej4dLUeVw65B13xEiwFB+AKGLnyLmHTsCLLWuD8Z4GRpUEEYFy6RGEDM9+KRHO3RFsAhNeCW0=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: testforstephen/testtravis
    tags: true
    all_branches: true
    condition: $TRAVIS_OS_NAME == "linux"
